name: Deploy Docs

on:
  push:

jobs:
  publish:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        deployments: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          steps:
            - cd docs
            - pnpm install
            - pnpm run build

        - name: Pages deploy
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: spud-docs
            directory: docs/dist
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
            branch: main
            workingDirectory: docs

      
    