name: Deploy Docs

on:
  push:

jobs:
  publish:
      environment: docs
      runs-on: ubuntu-latest
      permissions:
        contents: read
        deployments: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - uses: pnpm/action-setup@v2
          name: Install pnpm
          with:
            version: 8
            run_install: false

        - name: Build
          run: |
            cd docs
            pnpm install
            pnpm run build

        - name: Pages deploy
          uses: cloudflare/pages-action@v1
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: spud-docs
            directory: dist
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
            branch: main
            workingDirectory: docs
